name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          packages: sqlite3
          # Shouldn't upload debug logs for this package.
      - uses: ./
        with:
          packages: gcc-multilib
          debug: 'true' # Should upload debug logs for this package.
